/* 
 This file was generated by Dashcode.  
 You may edit this file to customize your widget or web page 
 according to the license.txt file included in the project.
 */

//
// Function: load()
// Called by HTML body element's onload event when the web application is ready to start
//
function load()
{
    dashcode.setupParts();
    
    var   tf   =   document.getElementById('textarea'); 
    var qs = "";
    var q = location.href;
    var rolld = String( Math.floor(Math.random()*100+1));
    
    var resultstr = q.substr(q.indexOf("UDID=")+5,40) ;
    resultstr = "你的udid是"+resultstr;
    resultstr += "\n\n你roll出了";
    resultstr += rolld;
    resultstr += "点(1-100)";

    
    tf.innerText = resultstr;
    hide_address_bar ();    
}





function hide_address_bar () {
  window.scrollTo(0, 1);
  setTimeout(function () {
    window.scrollTo(0, 0);
  }, 0);
};


function myClickHandler(event)
{

}
